import { defineConfig } from 'oxlint';

export const eslint = () => defineConfig({
  plugins: [
    'eslint',
  ],
  rules: {
    // 'eslint/accessor-pairs': 'off',
    // 'eslint/array-callback-return': 'off',
    // 'eslint/arrow-body-style': 'off',
    // 'eslint/block-scoped-var': 'off',
    // 'eslint/capitalized-comments': 'off',
    // 'eslint/class-methods-use-this': 'off',
    // 'eslint/complexity': 'off',
    'eslint/constructor-super': 'error',
    // 'eslint/curly': 'off',
    // 'eslint/default-case': 'off',
    // 'eslint/default-case-last': 'off',
    // 'eslint/default-param-last': 'off',
    // 'eslint/eqeqeq': 'off',
    'eslint/for-direction': 'error',
    // 'eslint/func-names': 'off',
    'eslint/func-style': ['error', 'expression'],
    'eslint/getter-return': 'error',
    // 'eslint/grouped-accessor-pairs': 'off',
    // 'eslint/guard-for-in': 'off',
    // 'eslint/id-length': 'off',
    // 'eslint/init-declarations': 'off',
    // 'eslint/max-classes-per-file': 'off',
    // 'eslint/max-depth': 'off',
    // 'eslint/max-lines': 'off',
    // 'eslint/max-lines-per-function': 'off',
    // 'eslint/max-nested-callbacks': 'off',
    // 'eslint/max-params': 'off',
    // 'eslint/max-statements': 'off',
    // 'eslint/new-cap': 'off',
    // 'eslint/no-alert': 'off',
    // 'eslint/no-array-constructor': 'off',
    'eslint/no-async-promise-executor': 'error',
    // 'eslint/no-await-in-loop': 'off',
    // 'eslint/no-bitwise': 'off',
    // 'eslint/no-caller': 'off',
    'eslint/no-case-declarations': 'error',
    'eslint/no-class-assign': 'error',
    'eslint/no-compare-neg-zero': 'error',
    'eslint/no-cond-assign': 'error',
    // 'eslint/no-console': 'off',
    'eslint/no-const-assign': 'error',
    'eslint/no-constant-binary-expression': 'error',
    'eslint/no-constant-condition': 'error',
    // 'eslint/no-constructor-return': 'off',
    // 'eslint/no-continue': 'off',
    'eslint/no-control-regex': 'error',
    'eslint/no-debugger': 'error',
    'eslint/no-delete-var': 'error',
    // 'eslint/no-div-regex': 'off',
    'eslint/no-dupe-class-members': 'error',
    'eslint/no-dupe-else-if': 'error',
    'eslint/no-dupe-keys': 'error',
    'eslint/no-duplicate-case': 'error',
    // 'eslint/no-duplicate-imports': 'off',
    // 'eslint/no-else-return': 'off',
    'eslint/no-empty': 'error',
    'eslint/no-empty-character-class': 'error',
    // 'eslint/no-empty-function': 'off',
    'eslint/no-empty-pattern': 'error',
    'eslint/no-empty-static-block': 'error',
    // 'eslint/no-eq-null': 'off',
    // 'eslint/no-eval': 'off',
    'eslint/no-ex-assign': 'error',
    // 'eslint/no-extend-native': 'off',
    // 'eslint/no-extra-bind': 'off',
    'eslint/no-extra-boolean-cast': 'error',
    // 'eslint/no-extra-label': 'off',
    'eslint/no-fallthrough': 'error',
    'eslint/no-func-assign': 'error',
    'eslint/no-global-assign': 'error',
    // 'eslint/no-implicit-coercion': 'off',
    'eslint/no-import-assign': 'error',
    // 'eslint/no-inline-comments': 'off',
    // 'eslint/no-inner-declarations': 'off',
    'eslint/no-invalid-regexp': 'error',
    'eslint/no-irregular-whitespace': 'error',
    // 'eslint/no-iterator': 'off',
    // 'eslint/no-label-var': 'off',
    // 'eslint/no-labels': 'off',
    // 'eslint/no-lone-blocks': 'off',
    // 'eslint/no-lonely-if': 'off',
    // 'eslint/no-loop-func': 'off',
    'eslint/no-loss-of-precision': 'error',
    // 'eslint/no-magic-numbers': 'off',
    'eslint/no-misleading-character-class': 'error',
    // 'eslint/no-multi-assign': 'off',
    // 'eslint/no-multi-str': 'off',
    'eslint/no-negated-condition': 'error',
    'eslint/no-nested-ternary': 'off',
    // 'eslint/no-new': 'off',
    // 'eslint/no-new-func': 'off',
    'eslint/no-new-native-nonconstructor': 'error',
    // 'eslint/no-new-wrappers': 'off',
    'eslint/no-nonoctal-decimal-escape': 'error',
    'eslint/no-obj-calls': 'error',
    // 'eslint/no-object-constructor': 'off',
    // 'eslint/no-param-reassign': 'off',
    // 'eslint/no-plusplus': 'off',
    // 'eslint/no-promise-executor-return': 'off',
    // 'eslint/no-proto': 'off',
    'eslint/no-prototype-builtins': 'error',
    'eslint/no-redeclare': 'error',
    'eslint/no-regex-spaces': 'error',
    // 'eslint/no-restricted-globals': 'off',
    // 'eslint/no-restricted-imports': 'off',
    // 'eslint/no-return-assign': 'off',
    // 'eslint/no-script-url': 'off',
    'eslint/no-self-assign': 'error',
    // 'eslint/no-self-compare': 'off',
    // 'eslint/no-sequences': 'off',
    'eslint/no-setter-return': 'error',
    // 'eslint/no-shadow': 'off',
    'eslint/no-shadow-restricted-names': 'error',
    'eslint/no-sparse-arrays': 'error',
    // 'eslint/no-template-curly-in-string': 'off',
    // 'eslint/no-ternary': 'off',
    'eslint/no-this-before-super': 'error',
    // 'eslint/no-throw-literal': 'off',
    // 'eslint/no-unassigned-vars': 'off',
    'eslint/no-undef': 'error',
    // 'eslint/no-undefined': 'off',
    'eslint/no-unexpected-multiline': 'error',
    // 'eslint/no-unmodified-loop-condition': 'off',
    // 'eslint/no-unneeded-ternary': 'off',
    'eslint/no-unreachable': 'error',
    'eslint/no-unsafe-finally': 'error',
    'eslint/no-unsafe-negation': 'error',
    'eslint/no-unsafe-optional-chaining': 'error',
    // 'eslint/no-unused-expressions': 'off',
    'eslint/no-unused-labels': 'error',
    'eslint/no-unused-private-class-members': 'error',
    'eslint/no-unused-vars': 'off',
    // 'eslint/no-use-before-define': 'off',
    'eslint/no-useless-backreference': 'error',
    // 'eslint/no-useless-call': 'off',
    'eslint/no-useless-catch': 'error',
    // 'eslint/no-useless-computed-key': 'off',
    // 'eslint/no-useless-concat': 'off',
    // 'eslint/no-useless-constructor': 'off',
    'eslint/no-useless-escape': 'error',
    // 'eslint/no-useless-rename': 'off',
    // 'eslint/no-useless-return': 'off',
    'eslint/no-var': 'error',
    // 'eslint/no-void': 'off',
    // 'eslint/no-warning-comments': 'off',
    'eslint/no-with': 'error',
    // 'eslint/operator-assignment': 'off',
    'eslint/prefer-const': 'error',
    // 'eslint/prefer-destructuring': 'off',
    // 'eslint/prefer-exponentiation-operator': 'off',
    // 'eslint/prefer-numeric-literals': 'off',
    // 'eslint/prefer-object-has-own': 'off',
    // 'eslint/prefer-object-spread': 'off',
    // 'eslint/prefer-promise-reject-errors': 'off',
    'eslint/prefer-rest-params': 'error',
    'eslint/prefer-spread': 'error',
    // 'eslint/prefer-template': 'off',
    // 'eslint/preserve-caught-error': 'off',
    // 'eslint/radix': 'off',
    // 'eslint/require-await': 'off',
    'eslint/require-yield': 'error',
    // 'eslint/sort-imports': 'off',
    // 'eslint/sort-keys': 'off',
    // 'eslint/sort-vars': 'off',
    // 'eslint/symbol-description': 'off',
    // 'eslint/unicode-bom': 'off',
    'eslint/use-isnan': 'error',
    'eslint/valid-typeof': 'error',
    // 'eslint/vars-on-top': 'off',
    // 'eslint/yoda': 'off',
  },
});
