import { defineConfig } from 'oxlint';

export const typescript = () => defineConfig({
  plugins: [
    'eslint',
    'typescript',
  ],
  options: {
    typeAware: true,
  },
  rules: {
    // Disable rules that are handled by typescript plugin
    'eslint/constructor-super': 'off',
    'eslint/getter-return': 'off',
    'eslint/no-class-assign': 'off',
    'eslint/no-const-assign': 'off',
    'eslint/no-dupe-class-members': 'off',
    'eslint/no-dupe-keys': 'off',
    'eslint/no-func-assign': 'off',
    'eslint/no-import-assign': 'off',
    'eslint/no-new-native-nonconstructor': 'off',
    'eslint/no-obj-calls': 'off',
    'eslint/no-redeclare': 'off',
    'eslint/no-setter-return': 'off',
    'eslint/no-this-before-super': 'off',
    'eslint/no-throw-literal': 'off',
    'eslint/no-undef': 'off',
    'eslint/no-unreachable': 'off',
    'eslint/no-unsafe-negation': 'off',
    'eslint/no-with': 'off',
    'eslint/prefer-promise-reject-errors': 'off',
    'eslint/require-await': 'off',

    // Built-in typescript plugin
    // 'typescript/adjacent-overload-signatures': 'off',
    // 'typescript/array-type': 'off',
    'typescript/await-thenable': 'error',
    'typescript/ban-ts-comment': 'error',
    // 'typescript/ban-tslint-comment': 'off',
    // 'typescript/class-literal-property-style': 'off',
    // 'typescript/class-methods-use-this': 'off',
    // 'class-methods-use-this': 'off',
    // 'typescript/consistent-generic-constructors': 'off',
    // 'typescript/consistent-indexed-object-style': 'off',
    // 'typescript/consistent-return': 'off',
    // 'typescript/consistent-type-assertions': 'off',
    // 'typescript/consistent-type-definitions': 'off',
    // 'typescript/consistent-type-exports': 'off',
    'typescript/consistent-type-imports': ['error', {
      prefer: 'type-imports',
    }],
    // 'typescript/default-param-last': 'off',
    // 'default-param-last': 'off',
    // 'typescript/dot-notation': 'off',
    // 'typescript/explicit-function-return-type': 'off',
    // 'typescript/explicit-module-boundary-types': 'off',
    // 'typescript/init-declarations': 'off',
    // 'init-declarations': 'off',
    // 'typescript/max-params': 'off',
    // 'max-params': 'off',
    'typescript/no-array-delete': 'error',
    'typescript/no-base-to-string': 'error',
    // 'typescript/no-confusing-non-null-assertion': 'off',
    // 'typescript/no-confusing-void-expression': 'off',
    // 'typescript/no-deprecated': 'off',
    // 'typescript/no-dupe-class-members': 'off',
    // 'no-dupe-class-members': 'off',
    'typescript/no-duplicate-enum-values': 'error',
    'typescript/no-duplicate-type-constituents': 'error',
    // 'typescript/no-dynamic-delete': 'off',
    // 'typescript/no-empty-function': 'off',
    // 'no-empty-function': 'off',
    'typescript/no-empty-object-type': 'off',
    'typescript/no-explicit-any': 'error',
    'typescript/no-extra-non-null-assertion': 'error',
    // 'typescript/no-extraneous-class': 'off',
    'typescript/no-floating-promises': 'off',
    'typescript/no-for-in-array': 'error',
    'typescript/no-implied-eval': 'error',
    // 'no-implied-eval': 'off',
    // 'typescript/no-import-type-side-effects': 'off',
    // 'typescript/no-inferrable-types': 'off',
    // 'typescript/no-invalid-void-type': 'off',
    // 'typescript/no-loop-func': 'off',
    // 'no-loop-func': 'off',
    // 'typescript/no-magic-numbers': 'off',
    // 'no-magic-numbers': 'off',
    // 'typescript/no-meaningless-void-operator': 'off',
    'typescript/no-misused-new': 'error',
    'typescript/no-misused-promises': ['error', {
      checksVoidReturn: {
        attributes: false,
      },
    }],
    // 'typescript/no-misused-spread': 'off',
    // 'typescript/no-mixed-enums': 'off',
    'typescript/no-namespace': 'error',
    // 'typescript/no-non-null-asserted-nullish-coalescing': 'off',
    'typescript/no-non-null-asserted-optional-chain': 'error',
    // 'typescript/no-non-null-assertion': 'off',
    // 'typescript/no-redeclare': 'off',
    // 'no-redeclare': 'off',
    'typescript/no-redundant-type-constituents': 'error',
    'typescript/no-require-imports': 'error',
    // 'typescript/no-restricted-imports': 'off',
    // 'no-restricted-imports': 'off',
    // 'typescript/no-restricted-types': 'off',
    // 'typescript/no-shadow': 'off',
    // 'no-shadow': 'off',
    'typescript/no-this-alias': 'error',
    // 'typescript/no-unnecessary-boolean-literal-compare': 'off',
    // 'typescript/no-unnecessary-condition': 'off',
    // 'typescript/no-unnecessary-parameter-property-assignment': 'off',
    // 'typescript/no-unnecessary-qualifier': 'off',
    // 'typescript/no-unnecessary-template-expression': 'off',
    // 'typescript/no-unnecessary-type-arguments': 'off',
    'typescript/no-unnecessary-type-assertion': 'error',
    'typescript/no-unnecessary-type-constraint': 'error',
    // 'typescript/no-unnecessary-type-conversion': 'off',
    // 'typescript/no-unnecessary-type-parameters': 'off',
    'typescript/no-unsafe-argument': 'error',
    'typescript/no-unsafe-assignment': 'error',
    'typescript/no-unsafe-call': 'error',
    'typescript/no-unsafe-declaration-merging': 'error',
    'typescript/no-unsafe-enum-comparison': 'error',
    'typescript/no-unsafe-function-type': 'error',
    'typescript/no-unsafe-member-access': 'error',
    'typescript/no-unsafe-return': 'error',
    // 'typescript/no-unsafe-type-assertion': 'off',
    'typescript/no-unsafe-unary-minus': 'error',
    // 'typescript/no-use-before-define': 'off',
    // 'no-use-before-define': 'off',
    // 'typescript/no-useless-constructor': 'off',
    // 'no-useless-constructor': 'off',
    // 'typescript/no-useless-default-assignment': 'off',
    // 'typescript/no-useless-empty-export': 'off',
    'typescript/no-wrapper-object-types': 'error',
    // 'typescript/non-nullable-type-assertion-style': 'off',
    'typescript/only-throw-error': 'error',
    // 'typescript/parameter-properties': 'off',
    'typescript/prefer-as-const': 'error',
    // 'typescript/prefer-enum-initializers': 'off',
    // 'typescript/prefer-find': 'off',
    // 'typescript/prefer-for-of': 'off',
    // 'typescript/prefer-function-type': 'off',
    // 'typescript/prefer-includes': 'off',
    // 'typescript/prefer-literal-enum-member': 'off',
    'typescript/prefer-namespace-keyword': 'error',
    // 'typescript/prefer-nullish-coalescing': 'off',
    // 'typescript/prefer-optional-chain': 'off',
    'typescript/prefer-promise-reject-errors': 'error',
    // 'typescript/prefer-readonly': 'off',
    // 'typescript/prefer-readonly-parameter-types': 'off',
    // 'typescript/prefer-reduce-type-parameter': 'off',
    // 'typescript/prefer-regexp-exec': 'off',
    // 'typescript/prefer-return-this-type': 'off',
    // 'typescript/prefer-string-starts-ends-with': 'off',
    // 'typescript/promise-function-async': 'off',
    // 'typescript/related-getter-setter-pairs': 'off',
    // 'typescript/require-array-sort-compare': 'off',
    'typescript/require-await': 'error',
    'typescript/restrict-plus-operands': 'error',
    'typescript/restrict-template-expressions': 'error',
    // 'typescript/return-await': 'off',
    // 'no-return-await': 'off',
    // 'typescript/strict-boolean-expressions': 'off',
    // 'typescript/switch-exhaustiveness-check': 'off',
    'typescript/triple-slash-reference': 'error',
    'typescript/unbound-method': 'error',
    // 'typescript/unified-signatures': 'off',
    // 'typescript/use-unknown-in-catch-callback-variable': 'off',

    // typescript-eslint
    // 'typescript-js/explicit-member-accessibility': 'off',
    // 'typescript-js/member-ordering': 'off',
    // 'typescript-js/method-signature-style': 'off',
    // 'typescript-js/naming-convention': 'off',
    // 'typescript-js/no-unused-private-class-members': 'off',
    // 'no-unused-private-class-members': 'off'
    // 'typescript-js/prefer-destructuring': 'off',
    // 'prefer-destructuring': 'off',
  },
  overrides: [
    {
      files: [
        '**/*.test.*',
        '**/*.test-d.*',
        '**/__tests__/**/*',
      ],
      rules: {
        'typescript/ban-ts-comment': 'off',
      },
    },
  ],
});
