import { defineConfig } from 'oxlint';

export const vitest = () => defineConfig({
  overrides: [
    {
      files: [
        '**/*.test.*',
        '**/*.test-d.*',
        '**/__tests__/**/*',
      ],
      plugins: [
        'vitest',
      ],
      rules: {
        // 'vitest/consistent-each-for': 'off',
        // 'vitest/consistent-test-filename': 'off',
        // 'vitest/consistent-test-it': 'off',
        // 'vitest/consistent-vitest-vi': 'off',
        'vitest/expect-expect': 'error',
        // 'vitest/hoisted-apis-on-top': 'off',
        // 'vitest/max-expects': 'off',
        // 'vitest/max-nested-describe': 'off',
        // 'vitest/no-alias-methods': 'off',
        'vitest/no-commented-out-tests': 'error',
        // 'vitest/no-conditional-expect': 'off',
        // 'vitest/no-conditional-in-test': 'off',
        // 'vitest/no-conditional-tests': 'off',
        // 'vitest/no-disabled-tests': 'off',
        // 'vitest/no-duplicate-hooks': 'off',
        // 'vitest/no-focused-tests': 'off',
        // 'vitest/no-hooks': 'off',
        'vitest/no-identical-title': 'error',
        'vitest/no-import-node-test': 'error',
        // 'vitest/no-importing-vitest-globals': 'off',
        // 'vitest/no-interpolation-in-snapshots': 'off',
        // 'vitest/no-large-snapshots': 'off',
        // 'vitest/no-mocks-import': 'off',
        // 'vitest/no-restricted-jest-methods': 'off',
        // 'vitest/no-restricted-matchers': 'off',
        // 'vitest/no-standalone-expect': 'off',
        // 'vitest/no-test-prefixes': 'off',
        // 'vitest/no-test-return-statement': 'off',
        // 'vitest/no-unneeded-async-expect-function': 'off',
        // 'vitest/prefer-called-once': 'off',
        // 'vitest/prefer-called-times': 'off',
        // 'vitest/prefer-called-with': 'off',
        // 'vitest/prefer-comparison-matcher': 'off',
        // 'vitest/prefer-describe-function-title': 'off',
        // 'vitest/prefer-each': 'off',
        // 'vitest/prefer-equality-matcher': 'off',
        // 'vitest/prefer-expect-resolves': 'off',
        // 'vitest/prefer-expect-type-of': 'off',
        // 'vitest/prefer-hooks-in-order': 'off',
        // 'vitest/prefer-hooks-on-top': 'off',
        // 'vitest/prefer-import-in-mock': 'off',
        // 'vitest/prefer-lowercase-title': 'off',
        // 'vitest/prefer-mock-promise-shorthand': 'off',
        // 'vitest/prefer-mock-return-shorthand': 'off',
        // 'vitest/prefer-spy-on': 'off',
        // 'vitest/prefer-strict-equal': 'off',
        // 'vitest/prefer-to-be': 'off',
        // 'vitest/prefer-to-be-falsy': 'off',
        // 'vitest/prefer-to-be-object': 'off',
        // 'vitest/prefer-to-be-truthy': 'off',
        // 'vitest/prefer-to-contain': 'off',
        // 'vitest/prefer-to-have-length': 'off',
        // 'vitest/prefer-todo': 'off',
        // 'vitest/require-hook': 'off',
        'vitest/require-local-test-context-for-concurrent-snapshots': 'error',
        'vitest/require-mock-type-parameters': 'off',
        // 'vitest/require-to-throw-message': 'off',
        // 'vitest/require-top-level-describe': 'off',
        'vitest/valid-describe-callback': 'error',
        'vitest/valid-expect': 'error',
        // 'vitest/warn-todo': 'off',
      },
    },
  ],
});
