import { defineConfig } from 'oxlint';

export const react = () => defineConfig({
  plugins: [
    'react',
  ],
  rules: {
    // Not Built-in react plugin
    // 'react-js/boolean-prop-naming': 'off',
    // 'react-js/destructuring-assignment': 'off',
    // 'react-js/forbid-component-props': 'off',
    // 'react-js/function-component-definition': ['error', {
    //   namedComponents: 'arrow-function',
    //   unnamedComponents: 'arrow-function',
    // }],
    // 'react-js/hook-use-state': 'off',
    // 'react-js/jsx-no-bind': 'off',
    // 'react-js/jsx-no-leaked-render': 'off',
    // 'react-js/jsx-no-literals': 'off',
    // 'react-js/no-invalid-html-attribute': 'off',
    // 'react-js/no-adjacent-inline-elements': 'off',
    // 'react-js/no-arrow-function-lifecycle': 'off',
    // 'react-js/no-deprecated': 'error',
    // 'react-js/no-did-update-set-state': 'off',
    // 'react-js/no-unstable-nested-components': 'off',
    // 'react-js/no-object-type-as-default-prop': 'off',
    // 'react-js/prefer-stateless-function': 'off',
    // 'react-js/require-default-props': 'off',

    // Built-in react plugin
    // 'react/button-has-type': 'off',
    // 'react/checked-requires-onchange-or-readonly': 'off',
    'react/display-name': 'error',
    'react/exhaustive-deps': 'error',
    // 'react/forbid-dom-props': 'off',
    // 'react/forbid-elements': 'off',
    // 'react/forward-ref-uses-ref': 'off',
    // 'react/iframe-missing-sandbox': 'off',
    'react/jsx-boolean-value': 'error',
    'react/jsx-curly-brace-presence': ['error', {
      propElementValues: 'always'
    }],
    // 'react/jsx-filename-extension': 'off',
    'react/jsx-fragments': ['error', 'syntax'],
    'react/jsx-handler-names': ['error', {
      eventHandlerPrefix: 'handle',
      eventHandlerPropPrefix: 'on',
      checkLocalVariables: false,
      checkInlineFunction: false,
    }],
    'react/jsx-key': 'error',
    // 'react/jsx-max-depth': 'off',
    'react/jsx-no-comment-textnodes': 'error',
    // 'react/jsx-no-constructed-context-values': 'off',
    'react/jsx-no-duplicate-props': 'error',
    // 'react/jsx-no-script-url': 'off',
    'react/jsx-no-target-blank': 'error',
    'react/jsx-no-undef': 'error',
    'react/jsx-no-useless-fragment': 'error',
    // 'react/jsx-pascal-case': 'off',
    // 'react/jsx-props-no-spread-multi': 'off',
    // 'react/jsx-props-no-spreading': 'off',
    // 'react/no-array-index-key': 'off',
    'react/no-children-prop': 'error',
    // 'react/no-danger': 'off',
    'react/no-danger-with-children': 'error',
    // 'react/no-did-mount-set-state': 'off',
    'react/no-direct-mutation-state': 'error',
    'react/no-find-dom-node': 'error',
    'react/no-is-mounted': 'error',
    // 'react/no-multi-comp': 'off',
    // 'react/no-namespace': 'off',
    // 'react/no-redundant-should-component-update': 'off',
    'react/no-render-return-value': 'error',
    // 'react/no-set-state': 'off',
    'react/no-string-refs': 'error',
    // 'react/no-this-in-sfc': 'off',
    'react/no-unescaped-entities': 'error',
    'react/no-unknown-property': 'error',
    // 'react/no-unsafe': 'off',
    // 'react/no-will-update-set-state': 'off',
    // 'react/only-export-components': 'off',
    // 'react/prefer-es6-class': 'off',
    'react/react-in-jsx-scope': 'off',
    'react/require-render-return': 'error',
    'react/rules-of-hooks': 'error',
    'react/self-closing-comp': 'error',
    // 'react/state-in-constructor': 'off',
    // 'react/style-prop-object': 'off',
    // 'react/void-dom-elements-no-children': 'off',
  },
});
